class CreateAuthentications < ActiveRecord::Migration[5.0]
  def change
    create_table :authentications do |t|
      t.string :uid
      #this is the string generated by the provider that uniquely identifies a user.
      t.string :provider
      #the authorization provider
      t.string :token
      # an access token that is generated by the provider after successful authentication by the provider of our app and approved authorization by the user
      t.integer :user_id
      # the ID of the user stored in the app's database. 
      t.timestamps
    end
  end
end
